name: Deploy Dev

on:
  push:
    branches: [master]

concurrency: deploy-dev

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

        uses: silverhand-io/actions-node-pnpm-run-steps@v1.2.2

      - name: Build

      # See warning in https://pnpm.io/cli/prune
      - name: Prune
        run: rm -rf node_modules packages/*/node_modules && pnpm i
        env:
          NODE_ENV: production

      - name: Setup env
        working-directory: packages/core
        run: echo "$DEV_CORE_ENV" >> .env
        env:
          DEV_CORE_ENV: ${{ secrets.DEV_CORE_ENV }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEV_SSH_KEY }}
          known_hosts: ${{ secrets.DEV_SSH_KNOWN_HOSTS }}
          config: ${{ secrets.DEV_SSH_CONFIG }}

      - name: Rsync folder
        run: rsync --filter='exclude .git' -r -a --delete-before --ignore-times ./ $DEV_SERVER_IP:~/logto
        env:
          DEV_SERVER_IP: ${{ secrets.DEV_SERVER_IP }}

      - name: Sleep for 5 seconds
        run: sleep 5s

      - name: Health check
        env:
          DEV_SERVER_URL: ${{ secrets.DEV_SERVER_URL }}
